name: linux build & tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Install Bun (TS Runtime)
      run: |
        curl -fsSL https://bun.sh/install | bash

    - name: Run unit tests with Bun
      run: |
        ~/.bun/bin/bun ./tests/sort.test.ts &&
        ~/.bun/bin/bun ./tests/prof-utils.test.ts

    - name: Run unit tests with Deno
      run: |
        deno run ./tests/sort.test.ts &&
        deno run ./tests/prof-utils.test.ts
